<a href="https://colab.research.google.com/github/susant146/PyTorch_Basics_CNNmodels/blob/main/Pytorch_Tutorial.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

**All Imports Here**

In [ ]:
import torch
import numpy as np

In [ ]:
# Creating an empty tensor.
x = torch.empty(3,3)
x1 = torch.ones(3,3)
x2 = torch.rand(3,3)
x3 = torch.zeros(3,3)
print(x)
print('Torch ones matrix:', x1)
print('Torch rand matrix:', x2)
print('Torch zeros matrix:', x3)

tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]])
Torch ones matrix: tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]])
Torch rand matrix: tensor([[0.1553, 0.6395, 0.9993],
        [0.8629, 0.1108, 0.3929],
        [0.3458, 0.4719, 0.2524]])
Torch zeros matrix: tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]])


**Basic Operations with Torch tensor**

In [ ]:
x = torch.rand(2,2)
y = torch.rand(2,2)

z = x + y
print('Addition:', z)

z1 = torch.add(x,y)
print('Addition:', z1)

# Inplace addition
y.add_(x)
print('Inplace Addition:', y)

Addition: tensor([[0.6741, 1.0557],
        [1.1551, 0.6968]])
Addition: tensor([[0.6741, 1.0557],
        [1.1551, 0.6968]])
Inplace Addition: tensor([[0.6741, 1.0557],
        [1.1551, 0.6968]])


In [ ]:
# Other Operations
z = y - x
print('Subtraction:', z)
z1 = torch.subtract(y,x)
print(f'Subtraction: {z1}')

z1.subtract_(y)
print(f'Inplace subtraction: {z1}')

Subtraction: tensor([[0.2887, 0.3532],
        [0.2562, 0.6531]])
Subtraction: tensor([[0.2887, 0.3532],
        [0.2562, 0.6531]])
Inplace subtraction: tensor([[-0.3853, -0.7025],
        [-0.8989, -0.0437]])


In [ ]:
# Multiplication and Division
x = torch.rand(2,2)
y = torch.rand(2,2)

z = x*y
print('Multiplication: ', z)
z1 = torch.multiply(x,y) # torch.mul and torch.multiply
print('Element-Wise Multiplication:', z1)
# Inplace multiplication: y.multiply_(x)

z = x / y # torch.div(x,y)
print('Element-Wise Division: \n', z)
y.div_(x)
print('Inplace Division: \n', y)

# Matrix multiplications
# Define two matrices
A = torch.tensor([[1, 2], [3, 4]])  # 2x2 matrix
B = torch.tensor([[5, 6, 1], [7, 8, 0]])  # 2x2 matrix

# Perform matrix multiplication
# Must follow the matrix multiplication rule
C = torch.mm(A, B)  # Method 1: torch.mm for 2D matrices
print("Matrix Multiplication Result (torch.mm):")
print(C)

# Alternative method: Using torch.matmul (supports broadcasting for higher dimensions)
C_broadcast = torch.matmul(A, B)
print("\nMatrix Multiplication Result (torch.matmul):")
print(C_broadcast)

Multiplication:  tensor([[0.0664, 0.6370],
        [0.1165, 0.1079]])
Element-Wise Multiplication: tensor([[0.0664, 0.6370],
        [0.1165, 0.1079]])
Element-Wise Division: 
 tensor([[7.2338, 1.2554],
        [0.3155, 5.3769]])
Inplace Division: 
 tensor([[0.1382, 0.7965],
        [3.1700, 0.1860]])
Matrix Multiplication Result (torch.mm):
tensor([[19, 22,  1],
        [43, 50,  3]])

Matrix Multiplication Result (torch.matmul):
tensor([[19, 22,  1],
        [43, 50,  3]])


In [ ]:
# Slicing operation same as numpy
x = torch.rand(5,4)
print(f"Random Matrix \n: {x}")

# All row first column (Index start with 0 in python)
print(f"All Row first column: \n {x[:,0]}")
print(f"All column first row: \n {x[0,:]}")
print(f"Few from both row and column: \n {x[0:2, 1:3]}")
# One element slicing
print(x[1,1])
print(f"one Element item: \n {x[0,1].item()}")


Random Matrix 
: tensor([[0.6066, 0.3364, 0.6849, 0.2754],
        [0.5498, 0.3176, 0.7805, 0.8700],
        [0.1993, 0.7023, 0.3729, 0.9300],
        [0.8145, 0.1704, 0.3050, 0.0548],
        [0.8762, 0.8749, 0.7048, 0.4081]])
All Row first column: 
 tensor([0.6066, 0.5498, 0.1993, 0.8145, 0.8762])
All column first row: 
 tensor([0.6066, 0.3364, 0.6849, 0.2754])
Few from both row and column: 
 tensor([[0.3364, 0.6849],
        [0.3176, 0.7805]])
tensor(0.3176)
one Element item: 
 0.3363545536994934


In [ ]:
# reshaping vs view: PyTorch commands to reshape tensors
# Create a tensor
tensor = torch.arange(12)  # 1D tensor with values from 0 to 11
print("Original Tensor:")
print(tensor)

# Reshape to 3x4 matrix
reshaped_tensor = tensor.reshape(3, 4)
print("\nReshaped to 3x4:")
print(reshaped_tensor)

# Reshape back to 1D
flattened_tensor = reshaped_tensor.reshape(-1)
print("\nFlattened Tensor:")
print(flattened_tensor)

Original Tensor:
tensor([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

Reshaped to 3x4:
tensor([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]])

Flattened Tensor:
tensor([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])


In [ ]:
# Reshape to 2x6 using view
# reshape: Works regardless of tensor's memory layout.
# view: Faster but requires the tensor to have contiguous memory. Use .contiguous() before view if needed.
reshaped_view = tensor.view(2, 6)
print("\nReshaped to 2x6 using view:")
print(reshaped_view)


# Ensuring contiguity before view
non_contiguous = tensor.t()
contiguous_tensor = non_contiguous.contiguous().view(-1)


Reshaped to 2x6 using view:
tensor([[ 0,  1,  2,  3,  4,  5],
        [ 6,  7,  8,  9, 10, 11]])


In [ ]:
# Automatically infer one dimension
# Use -1 to let PyTorch infer the size of one dimension.
inferred_shape = tensor.reshape(3, -1)
print("\nReshaped with Inferred Dimension (2x-1):")
print(inferred_shape)


Reshaped with Inferred Dimension (2x-1):
tensor([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]])


**Numpy to PyTorch Tensor & Vice-Versa**

In [ ]:
a = torch.ones(5)
print(a)

b = a.numpy()
print('Numpy array: \n', b)
print('Type: \t', type(b))

# need to be very careful with place operations
a.add_(2)
print('Modified a: \n', a)
print('See What happend! \n', b)

tensor([1., 1., 1., 1., 1.])
Numpy array: 
 [1. 1. 1. 1. 1.]
Type: 	 <class 'numpy.ndarray'>
Modified a: 
 tensor([3., 3., 3., 3., 3.])
See What happend! 
 [3. 3. 3. 3. 3.]


In [ ]:
a = np.ones(5)
print(a)
b = torch.from_numpy(a) # default dtype is float64, change
# b = b.to(dtype=torch.int)  # or b = b.type(torch.IntTensor)
print(b)

# Inplace operation
a += 1
print('a ndarray: \t',a)
print('b Tensor: \t',b)

# Check this one
a = a+1
print('a ndarray: \t',a)
print('b Tensor: \t',b)

[1. 1. 1. 1. 1.]
tensor([1., 1., 1., 1., 1.], dtype=torch.float64)
a ndarray: 	 [2. 2. 2. 2. 2.]
b Tensor: 	 tensor([2., 2., 2., 2., 2.], dtype=torch.float64)
a ndarray: 	 [3. 3. 3. 3. 3.]
b Tensor: 	 tensor([2., 2., 2., 2., 2.], dtype=torch.float64)


**Check for Available Device:** *Cuda or CPU*

In [ ]:
if torch.cuda.is_available():
    device = torch.device("cuda")  # Use GPU
    print("CUDA is available. Using GPU.")
else:
    device = torch.device("cpu")  # Use CPU
    print("CUDA is not available. Using CPU.")

x = torch.ones(5, device=device)
y = torch.ones(5)
y = y.to(device)
z = x + y
print(f'The operation performed in {device}, output: {z}')

# As x, y and z are in CUDA, we can't convert them to numpy
# z1 = z.numpy() # Error Here
# bringing z to cpu
z1 = z.cpu()
z1 = z1.numpy()
print(f"z1 is in cpu, output ndarray: {z1}")

CUDA is available. Using GPU.
The operation performed in cuda, output: tensor([2., 2., 2., 2., 2.], device='cuda:0')
z1 is in cpu, output: [2. 2. 2. 2. 2.]
